# Generated by Django 4.1.7 on 2023-03-27 22:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DermaCareApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Commenter_name', models.CharField(max_length=100)),
                ('date_commented', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_content', models.TextField()),
                ('BlogPosts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BlogCommenst', to='DermaCareApp.blogpost')),
            ],
        ),
    ]
