# Generated by Django 4.1.7 on 2023-03-28 15:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DermaCareApp', '0002_blogcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.ImageField(upload_to='WebLogoImageFolder')),
                ('admin', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
