# Generated by Django 4.1.7 on 2023-03-29 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DermaCareApp', '0006_dermatologist_gender_patient_gender_user_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dermatologist',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
