# Generated by Django 4.1.7 on 2023-03-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DermaCareApp', '0007_remove_dermatologist_gender_remove_patient_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dermatologist',
            name='agree',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='agree',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='agree',
            field=models.BooleanField(default=False),
        ),
    ]
