# Generated by Django 4.1.7 on 2023-03-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DermaCareApp', '0009_patient_gender_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='dermatologist',
            name='DermaCV_File',
            field=models.FileField(default='', upload_to='DermaCV_File_Folder'),
        ),
        migrations.AddField(
            model_name='dermatologist',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='dermatologist',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dermatologist',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='DermaCV_File',
            field=models.FileField(default='', upload_to='DermaCV_File_Folder'),
        ),
        migrations.AlterField(
            model_name='dermatologist',
            name='speciality',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
