# Generated by Django 4.1.7 on 2023-03-31 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DermaCareApp', '0010_dermatologist_dermacv_file_dermatologist_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dermatologist',
            name='DermaCV_File',
        ),
        migrations.RemoveField(
            model_name='user',
            name='DermaCV_File',
        ),
    ]
