# Generated by Django 4.1.7 on 2023-03-31 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DermaCareApp', '0012_remove_dermatologist_gender_remove_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dermatologist',
            name='agree',
        ),
        migrations.RemoveField(
            model_name='dermatologist',
            name='location',
        ),
        migrations.RemoveField(
            model_name='dermatologist',
            name='phone',
        ),
    ]
