# Generated by Django 4.1.7 on 2023-04-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DermaCareApp', '0014_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='dermatologist',
            name='agree',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dermatologist',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='dermatologist',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dermatologist',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
