# Generated by Django 4.1.7 on 2023-04-04 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DermaCareApp', '0017_alter_blogcomment_blogposts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='BlogPosts',
            new_name='blogpost',
        ),
    ]
