# Generated by Django 4.1.7 on 2023-04-05 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DermaCareApp', '0018_rename_blogposts_blogcomment_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='Commenter_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
