# Generated by Django 4.1.7 on 2023-04-07 19:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DermaCareApp', '0020_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='comment_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
