# Generated by Django 4.1.7 on 2023-04-07 23:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DermaCareApp', '0022_alter_reply_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='sub_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
