# Generated by Django 4.1.7 on 2023-05-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DermaCareApp', '0023_blogpost_sub_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='dermatologist',
            name='DermaCV_File',
            field=models.FileField(default='', upload_to='Documents'),
        ),
        migrations.AddField(
            model_name='user',
            name='DermaCV_File',
            field=models.FileField(default='', upload_to='DermaCV_File_Folder'),
        ),
    ]
