# Generated by Django 4.1.7 on 2023-05-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DermaCareApp', '0024_dermatologist_dermacv_file_user_dermacv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dermatologist',
            name='DermaCV_File',
            field=models.FileField(default='', upload_to='Documents/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='DermaCV_File',
            field=models.FileField(default='', upload_to='Documents/'),
        ),
    ]
