# Generated by Django 4.1.7 on 2023-05-09 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DermaCareApp', '0025_alter_dermatologist_dermacv_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='reply',
            new_name='reply_content',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='user',
            new_name='reply_name',
        ),
    ]
