# Generated by Django 4.1.7 on 2023-05-09 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DermaCareApp', '0026_rename_reply_reply_reply_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='reply_content',
            new_name='reply',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='reply_name',
            new_name='user',
        ),
    ]
