# Generated by Django 4.1.7 on 2023-05-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DermaCareApp', '0028_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DermaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derma_user_name', models.CharField(max_length=100)),
            ],
        ),
    ]
