# Generated by Django 4.1.7 on 2023-05-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DermaCareApp', '0030_appointment_derma_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='derma_user',
            field=models.CharField(default='', max_length=50),
        ),
    ]
