# Generated by Django 4.1.7 on 2023-05-10 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DermaCareApp', '0032_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-sent_date']},
        ),
    ]
