# Generated by Django 4.1.7 on 2023-06-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DermaCareApp', '0033_alter_appointment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtopicDermatitis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo_file', models.ImageField(upload_to='AtopicDermatitis/')),
            ],
        ),
        migrations.CreateModel(
            name='BasalCellCarcinoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo_file', models.ImageField(upload_to='BasalCellCarcinoma/')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo_file', models.ImageField(upload_to='All/')),
            ],
        ),
    ]
