# Generated by Django 4.1.7 on 2023-06-11 19:43

import DermaCareApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DermaCareApp', '0034_atopicdermatitis_basalcellcarcinoma_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone_no',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Invalid Phone number', regex='^\\+?251?\\d{9,15}$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='prefered_date_time',
            field=models.DateTimeField(null=True, validators=[DermaCareApp.models.validate_future_datetime]),
        ),
    ]
