# Generated by Django 4.1.7 on 2023-06-11 20:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DermaCareApp', '0036_alter_appointment_derma_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(max_length=50, validators=[django.core.validators.RegexValidator(message='Invalid Email Address', regex="^[A-Za-z0-9_!#$%&'*+\\/=?`{|}~^.-]+@[A-Za-z0-9.-]+$")]),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Invalid first name', regex='^([a-z]+)( [a-z]+)*( [a-z]+)*$')]),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Invalid last name', regex='^([a-z]+)( [a-z]+)*( [a-z]+)*$')]),
        ),
    ]
